# Generated by Django 2.0.5 on 2018-05-23 16:47

import MetroMap.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MetroMap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='segments',
        ),
        migrations.AddField(
            model_name='segment',
            name='line',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='MetroMap.Line'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='level',
            field=models.IntegerField(choices=[(0, 'Minor'), (1, 'Major'), (2, 'Interchange'), (3, 'Intercity')], default=MetroMap.models.Station.Level(0)),
        ),
    ]
