# Generated by Django 2.0.5 on 2018-06-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MetroMap', '0002_auto_20180523_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='attr',
            new_name='attrs',
        ),
    ]
