# Generated by Django 2.0.5 on 2018-06-29 16:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MetroMap', '0003_auto_20180603_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
